import Layout from "@/components/layout";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../styles/globals.css";
import Script from "next/script";
import settingsData from "../database/settings.json";

const { settings } = settingsData;

const Font = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Sidrat Almuntaha | سِدْرَةِ الْمُنْتَهَى",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr">
      <body className={`${Font.className} antialiased`}>
        <Layout>{children}</Layout>

        <Script id="dynamic-favicon" strategy="afterInteractive">
          {`
    (function () {
      const setFavicon = () => {
        const isDark = document.documentElement.classList.contains("dark");
        const existing = document.querySelector("link[rel='icon']");
        if (existing) existing.remove();

        const link = document.createElement("link");
        link.rel = "icon";
        link.type = "image/png";
        link.href = isDark
          ? "${process.env.NEXT_PUBLIC_UPLOADS_BASE_URL}${settings.faviconUrl}"
          : "${process.env.NEXT_PUBLIC_UPLOADS_BASE_URL}${settings.faviconDarkUrl}";
        document.head.appendChild(link);
      };

      // بار اول اجرا
      setFavicon();

      // گوش دادن به تغییر تم
      const observer = new MutationObserver(() => {
        setFavicon();
      });

      observer.observe(document.documentElement, {
        attributes: true,
        attributeFilter: ["class"],
      });
    })();
  `}
        </Script>
      </body>
    </html>
  );
}
